import Navbar from '@/components/navbar/main-nav'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { getServerSession } from 'next-auth'
import { getUserSession } from '@/lib/auth'
import { TProvider } from '@/providers/toast-provider'
import { prisma } from '@/lib/prisma'
import myUser from './actions/getUser'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const user =  await myUser();
  console.log(user);

  const courses = await prisma.course.findMany({
    where: {
        userId:user?.id
    }
  })

  return (
    <html lang="en">
      <body className={inter.className}>
        <TProvider/>
        <Navbar user={user} length={courses.length}/>
        {children}
        </body>
    </html>
  )
}
