import Navbar from '@/components/navbar/main-nav'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { TProvider } from '@/providers/toast-provider'
import "@uploadthing/react/styles.css";
import myUser from './actions/getUser'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const user = await myUser()

  return (
    <html lang="en">
      <body className={inter.className}>
        <TProvider/>
        <Navbar user={user}/>
        {children}
        </body>
    </html>
  )
}
